

# Adds a remove property to the Javascript Array object
# This function can remove by value
Array::remove = ->
  what = undefined
  a = arguments
  L = a.length
  ax = undefined
  while L and @length
    what = a[--L]
    while (ax = @indexOf(what)) != -1
      @splice ax, 1
  this




# ---
# generated by js2coffee 2.0.1